### ISSUE TITLE
New requirements.txt entry in mylar3

### ISSUE THREAD

**Issue by claym** [hotio/mylar3#11]
It looks like there was an addition to the requirements.txt last week

https://github.com/mylar3/mylar3/blob/64ad7b4b1aafcdb952814ba72d14be94295a4e6c/requirements.txt

user_agent2>=2021.12.11 

The guys in mylar #support are telling me this is causing an issue with ComicTagger.

**Comment by barbequesauce** [comment]
Related to https://github.com/mylar3/mylar3/issues/1131

**Comment by mrhotio** [comment]
have a looks at the new builds when they finish
